from .login import login_page
from .register import register_page
from .student_dashboard import student_dashboard
from .teacher_dashboard import teacher_dashboard
from .teacher_assignments import teacher_assignments
from .teacher_notes import teacher_notes
from .teacher_students import teacher_students
from .teacher_reports import teacher_reports
from .admin_dashboard import admin_dashboard
from .settings import settings_page
from .create_assignment import create_assignment
from .create_note import create_note
from .admin_assignments import admin_assignments
from .admin_notes import admin_notes
from .admin_students import admin_students
from .admin_attendance import admin_attendance
from .admin_reports import admin_reports
from .admin_internships import admin_internships_page
from .admin_teachers import admin_teachers_page
